### ISSUE TITLE
Unable to run first "Sample Size" example.

### ISSUE THREAD

**Issue by Muzietto** [pholser/junit-quickcheck#103]
I am trying to run the example related to [sample size](http://pholser.github.io/junit-quickcheck/site/0.6/usage/sample-size.html).

Each time I try to execute the test inside the `Geography` class I get a `com.pholser.junit.quickcheck.internal.ReflectionException`. The code that produces the error is [here](https://github.com/Muzietto/quick-java-check/tree/master/src/test/java/net/faustinelli/quickcheck/coordinate).

I am posting the stack trace as first comment to this issue.

By the way, the correct JUnit 4 assumption used in the `Geography.northernHemisphere` test method should be

     assumeTrue(c.latitude().compareTo(BigDecimal.ZERO) > 0);

as the `greaterThan` predicate seems to be not immediately available in every JUnit distro. At least not in mine, which happens to be the one offered standard with Intellij IDEA.

**Comment by Muzietto** [comment]
java.lang.InstantiationException: net.faustinelli.quickcheck.coordinate.Coordinates
com.pholser.junit.quickcheck.internal.ReflectionException: java.lang.InstantiationException: net.faustinelli.quickcheck.coordinate.Coordinates
	at com.pholser.junit.quickcheck.internal.Reflection.reflectionException(Reflection.java:251)
	at com.pholser.junit.quickcheck.internal.Reflection.instantiate(Reflection.java:109)
	at com.pholser.junit.quickcheck.internal.ParameterTypeContext.makeGenerator(ParameterTypeContext.java:160)
	at com.pholser.junit.quickcheck.internal.ParameterTypeContext.addGenerators(ParameterTypeContext.java:147)
	at com.pholser.junit.quickcheck.internal.ParameterTypeContext.annotate(ParameterTypeContext.java:132)
	at com.pholser.junit.quickcheck.internal.PropertyParameterContext.annotate(PropertyParameterContext.java:51)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.parameterContextFor(PropertyStatement.java:182)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$parameters$27(PropertyStatement.java:159)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.parameters(PropertyStatement.java:166)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:89)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pholser** [comment]
Generator `Coordinates` needs a `public` zero-arg constructor in order for junit-quickcheck to instantiate it. It looks like when you created generator `Coordinates`, your IDE generated two `protected` constructors that mirror the signatures of the superclass constructor. I'd change `Coordinates` to have a single ctor like so:

    public class Coordinates extends Generator<Coordinate> {
        public Coordinates() {
            super(Coordinate.class);
        }
    }

Hope this helps! I should have made the requirements on custom generators clearer in the docs. Sorry for the trouble.

**Comment by pholser** [comment]
Also -- sorry about the `greaterThan` confusion. That method lives on `org.hamcrest.Matchers`in the [Hamcrest](http://hamcrest.org/JavaHamcrest/) library.

**Comment by Muzietto** [comment]
Yeah, [the code](https://github.com/Muzietto/quick-java-check/tree/master/src/test/java/net/faustinelli/quickcheck/coordinate) is now working. Thank you.
Going to put this bit in the documentation changes that I propose.
