### ISSUE TITLE
Exception from shrunk example is not logged

### ISSUE THREAD

**Issue by tinkerware** [pholser/junit-quickcheck#124]
I like the presentation of falsified properties in 0.7-alpha1, except this one thing. If there's a smaller counter-example from shrinking, I really want to see the backtrace for that, instead of the original (and larger) counter-example:

```
java.lang.AssertionError: Property commutativeCombine falsified.
Original failure message: [high[=1984954367] < 2 * low[=1166016512]: a=HistogramSnapshot{count=1, range=RuntimeRange{1166016512,1167065087}}, b=HistogramSnapshot{count=1, range=RuntimeRange{1983905792,1984954367}}]
Original args: [HistogramSnapshot{count=1, range=RuntimeRange{1166016512,1167065087}}, HistogramSnapshot{count=1, range=RuntimeRange{1983905792,1984954367}}]
Args shrunken to: [HistogramSnapshot{count=1, range=RuntimeRange{992477184,993001471}}, HistogramSnapshot{count=1, range=RuntimeRange{1983905792,1984954367}}]
Seeds: [1908559894991300119, -3782965659388203707]

	at com.pholser.junit.quickcheck.runner.PropertyFalsified.smallerCounterexampleFound(PropertyFalsified.java:62)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.fail(ShrinkNode.java:103)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:103)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:158)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$41(PropertyStatement.java:132)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
(...)
Caused by: java.lang.AssertionError: high[=1984954367] < 2 * low[=1166016512]: a=HistogramSnapshot{count=1, range=RuntimeRange{1166016512,1167065087}}, b=HistogramSnapshot{count=1, range=RuntimeRange{1983905792,1984954367}}
```

I think it makes more sense to display the backtrace from the smaller example; it's almost always going to be more tractable to figure out what's going on there than in the larger examples.

**Comment by pholser** [comment]
@tinkerware I can resolve this. Thanks for the feedback!

**Comment by tinkerware** [comment]
Yes, that's better. Would that code path contain anything from the classes under test, the generators or the counter example hook you've added recently? If so, those stack frames should not be elided.

**Comment by pholser** [comment]
OK - I'll set about preserving as much context as I can.

**Comment by pholser** [comment]
Here's what I'm thinking of...

This property:

```java
public class Foo {
    private final int i;
    private final boolean marked;

    public Foo(int i) {
        this.i = i;
    }

    public int i() {
        return i;
    }

    @Override public int hashCode() {
        return i;
    }

    @Override public boolean equals(Object o) {
        return o instanceof Foo && ((Foo) o).i() == i;
    }

    @Override public String toString() {
        return "Foo[" + i + ']';
    }
}

    @RunWith(JUnitQuickcheck.class)
    public class ShrinkingCompletely {
        @Property(maxShrinks = Integer.MAX_VALUE, maxShrinkDepth = Integer.MAX_VALUE)
        public void shouldHold(Foo f) {
            assumeThat(f.i(), greaterThan(0));

            assertThat(f.i(), lessThan(1));
        }
    }
```

would yield something like this:

```
java.lang.AssertionError: Property shouldHold falsified.
Original failure message: [
Expected: a value less than <1>
     but: <1353697724> was greater than <1>]
Original args: [Foo[1353697724]]
Shrink failure message: [
Expected: a value less than <1>
     but: <1> was equal to <1>]
Args shrunken to: [Foo[1]]
Seeds: [4258792209962850693]


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.verifyProperty(ShrinkNode.java:95)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:82)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:158)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$7(PropertyStatement.java:132)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
Caused by: java.lang.AssertionError: 
Expected: a value less than <1>
     but: <1353697724> was greater than <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 17 more
```

Does this capture enough context? Could it be worded more clearly?

**Comment by tinkerware** [comment]
I'm assuming you meant to include the cause from the result of the shrink and not the first counter-example. I think the prologue looks good. For the backtrace, I really like it when root causes are printed at the top, rather than the bottom. Most Java software is guilty of that particular transgression, but it is particularly jarring in testing libraries.

**Comment by tinkerware** [comment]
Also, a short pointer to how to use the seed to recreate the failure after the printed seed would be helpful; I keep having to look it up every time I have to do it when I come back to property tests.

**Comment by pholser** [comment]
@tinkerware re: fixing the seed, there is [a bit on the site about this](http://pholser.github.io/junit-quickcheck/site/0.7-alpha-1/usage/seed.html). Would it help to include a hint in the assertion message?

**Comment by pholser** [comment]
@tinkerware At your convenience, would you mind to have a look at the pull request noted above? I want to make sure that the changes I've made will satisfy your needs.

I'm going to break this down by cases.

=====

If a counterexample is found, and shrinking is disabled, the exception will be something like:

```
java.lang.AssertionError: Property shouldHold falsified.
Failure message: [null]
Args: [Foo[1536448469]]
Seeds: [909100383591561840]

	at com.pholser.junit.quickcheck.runner.PropertyFalsified.counterexampleFound(PropertyFalsified.java:42)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$41(PropertyStatement.java:128)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
...
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.pholser.junit.quickcheck.ShrinkingTest$DisablingShrinking.shouldHold(ShrinkingTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	... 17 more
```

Here, the "cause" of the `AssertionError` with the fancy messaging is the assertion failure where the counterexample was actually detected. The stack trace of the `AssertionError` with the fancy messaging is that of the property verification actually tripping over the initial counterexample.

=====

If a counterexample is found, and shrinking fails to find a smaller counterexample, the exception will be something like:

```
java.lang.AssertionError: Property shouldHold falsified.
Failure message: [
Expected: a value less than <1073741823>
     but: <1353081228> was greater than <1073741823>]
Args: [Foo[1353081228]]
Seeds: [-6168442671370861181]

	at com.pholser.junit.quickcheck.runner.PropertyFalsified.counterexampleFound(PropertyFalsified.java:42)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.fail(ShrinkNode.java:117)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:103)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:158)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$41(PropertyStatement.java:132)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
...
Caused by: java.lang.AssertionError: 
Expected: a value less than <1073741823>
     but: <1353081228> was greater than <1073741823>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingNotReally.shouldHold(ShrinkingTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 17 more
```

Here, the "cause" of the `AssertionError` with the fancy messaging is the assertion failure where the counterexample was actually detected. The stack trace of the `AssertionError` with the fancy messaging is that of the shrinking mechanism actually failing to find a smaller counterexample, and raising an exception signaling the original counterexample.

=====

If shrinking finds a smaller counterexample, the exception will be something like:

```
java.lang.AssertionError: Property shouldHold falsified via shrinking.
Shrink failure message: [
Expected: a value less than <1>
     but: <1> was equal to <1>]
Shrunken args: [Foo[1]]
Original failure message: [
Expected: a value less than <1>
     but: <186026947> was greater than <1>]
Original args: [Foo[186026947]]
Seeds: [-8662619978135167120]


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.verifyProperty(ShrinkNode.java:98)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:82)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:158)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$41(PropertyStatement.java:132)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
...
Caused by: java.lang.AssertionError: 
Expected: a value less than <1>
     but: <186026947> was greater than <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 17 more
```

The "cause" here is that of the original counterexample being found. The top-level stack trace is that of the smaller counterexample being found.

=====

There are other cases, such as what happens if an unexpected exception is raised during property verification or shrinking, an assumption never met, etc. -- these shouldn't be different from what behavior was there before, maybe some cosmetic message changes.

Thanks for taking the time to look at this, and to report your findings!

**Comment by tinkerware** [comment]
The output for these cases look great. I'm going to look at the PR today.

**Comment by pholser** [comment]
@tinkerware This should be in 0.7 alpha 2. Please close this issue if that release remedies it. Thanks!

**Comment by tinkerware** [comment]
Works great, thanks!
