### ISSUE TITLE
Generator#addComponentGenerators is not implemented

### ISSUE THREAD

**Issue by marcoUnited** [pholser/junit-quickcheck#167]
Javadoc says:
_Adds component generators to this generator.

Some generators need component generators to create proper values. For example, list generators require a single component generator in order to generate elements that have the type of the list parameter's type argument.

Parameters:
newComponents - component generators to add_

I ran into this issue when I tried to create a List of Child-Objects within a Generator (using a Generator within a Generator). I am now unable to do this, is there another way that I haven't figured out?

**Comment by pholser** [comment]
@marcoUnited Thanks for your interest! Can you post a small example to demonstrate how you're using component generators? It would help diagnosis a lot. Appreciate it!

**Comment by marcoUnited** [comment]
@pholser Thank you for your fast response
I made a sample example for you to see what I am trying to achieve
`package simplified.model;

import java.util.List;

public class A {
    private String someString;
    private int someInt;
    private List<B> listOfB;
    public A(String someString, int someInt) {
        this.someString = someString;
        this.someInt = someInt;
    }

    public void setListOfB(List<B> listOfB) {
        this.listOfB = listOfB;
    }
}
package simplified.model;

public class B {
    private String someString;
    private int someInt;

    public B(String someString, int someInt) {
        this.someString = someString;
        this.someInt = someInt;
    }
}
package simplified;

import java.util.Arrays;

import com.pholser.junit.quickcheck.generator.GenerationStatus;
import com.pholser.junit.quickcheck.generator.Generator;
import com.pholser.junit.quickcheck.random.SourceOfRandomness;

import simplified.model.A;
import simplified.model.B;

public class AGenerator extends Generator<A> {
    public AGenerator() {
        super(A.class);
    }

    @Override
    public A generate(SourceOfRandomness sourceOfRandomness, GenerationStatus generationStatus) {
        final String someString = gen().type(String.class).generate(sourceOfRandomness, generationStatus);
        final int someInt = gen().type(int.class).generate(sourceOfRandomness, generationStatus);

        final A a = new A(someString, someInt);

        BGenerator bGenerator = new BGenerator();

        // the implementation of addComponentGenerators is empty
        // how to use/register a generator within a generator???
        addComponentGenerators(Arrays.asList(bGenerator));

        final B b1 = gen().type(B.class).generate(sourceOfRandomness, generationStatus);
        final B b2 = gen().type(B.class).generate(sourceOfRandomness, generationStatus);

        a.setListOfB(Arrays.asList(b1, b2));

        return a;
    }
}
package simplified;

import com.pholser.junit.quickcheck.generator.GenerationStatus;
import com.pholser.junit.quickcheck.generator.Generator;
import com.pholser.junit.quickcheck.random.SourceOfRandomness;

import simplified.model.B;

public class BGenerator extends Generator<B> {
    public BGenerator() {
        super(B.class);
    }

    @Override
    public B generate(SourceOfRandomness sourceOfRandomness, GenerationStatus generationStatus) {
        final String someString = gen().type(String.class).generate(sourceOfRandomness, generationStatus);
        final int someInt = gen().type(int.class).generate(sourceOfRandomness, generationStatus);

        return new B(someString, someInt);
    }
}
package simplified;

import org.junit.runner.RunWith;

import com.pholser.junit.quickcheck.From;
import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;

import simplified.model.A;

@RunWith(JUnitQuickcheck.class)
public class ATest {

    @Property
    public void test(@From(AGenerator.class) A a){
        System.out.println(a);
    }
}
`
When I run the ATest, then I get the following exception:
java.lang.IllegalArgumentException: Cannot find generator for simplified.model.B:simplified.model.B of type simplified.model.B

	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.matchingGenerators(GeneratorRepository.java:255)
	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.generatorFor(GeneratorRepository.java:236)
	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.produceGenerator(GeneratorRepository.java:215)
	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.type(GeneratorRepository.java:151)
	at simplified.AGenerator.generate(AGenerator.java:30)
	at simplified.AGenerator.generate(AGenerator.java:12)
	at com.pholser.junit.quickcheck.internal.generator.CompositeGenerator.generate(CompositeGenerator.java:54)
	at com.pholser.junit.quickcheck.internal.generator.PropertyParameterGenerationContext.generate(PropertyParameterGenerationContext.java:75)
	at com.pholser.junit.quickcheck.internal.SeededValue.<init>(SeededValue.java:12)
	at com.pholser.junit.quickcheck.runner.sampling.TupleParameterSampler$$Lambda$35.000000000F720EA0.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:204)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1385)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:719)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:510)
	at com.pholser.junit.quickcheck.runner.sampling.TupleParameterSampler.lambda$sample$44(TupleParameterSampler.java:56)
	at com.pholser.junit.quickcheck.runner.sampling.TupleParameterSampler$$Lambda$31.0000000011E72FA0.get(Unknown Source)
	at java.util.stream.StreamSpliterators$InfiniteSupplyingSpliterator$OfRef.tryAdvance(StreamSpliterators.java:1367)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:305)
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$34.000000000F720AB0.getAsBoolean(Unknown Source)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:217)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:172)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:311)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:692)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:104)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by pholser** [comment]
@marcoUnited `addComponentGenerators()` is really intended for junit-quickcheck itself to call, and has a meaningful implementation only in `ComponentizedGenerator`. I should probably clarify this in the documentation; I can see how it might be confusing.

If you're willing to register your generators with the `ServiceLoader`, your test might look like this:

```java
    @Override
    public A generate(SourceOfRandomness random, GenerationStatus status) {
        String someString = gen().type(String.class).generate(random, status);
        int someInt = gen().type(int.class).generate(random, status);

        A a = new A(someString, someInt);

        ArrayListGenerator listOfB = gen().make(ArrayListGenerator.class, gen().type(B.class));
        a.setListOfB(listOfB.generate(random, status));
        return a;
    }
```

I wonder if adding `gen().type(baseType, componentTypes...)` might make this a little easier. That way, you aren't telling junit-quickcheck "make me an ArrayListGenerator that makes instances of B as elements", you can say "make me a generator that makes Lists that have B as their element tye".

If you don't want to register your generators with the `ServiceLoader`, you need a way to tell junit-quickcheck to make things of type `List<B>`, and that the `B`'s should be produced from your (unregistered) `BGenerator`. Try using `gen().field()`, like so:

```java
public class AGenerator extends Generator<A> {
    private static final List<@From(BGenerator.class) B> LIST_OF_B = null;

    public AGenerator() {
        super(A.class);
    }

    @SuppressWarnings("unchecked")
    private Generator<List<B>> listOfB() {
        try {
            return (Generator<List<B>>) gen().field(getClass().getDeclaredField("LIST_OF_B"));
        } catch (NoSuchFieldException e) {
            throw new AssertionError(e);
        }
    }

    @Override
    public A generate(SourceOfRandomness random, GenerationStatus status) {
        String someString = gen().type(String.class).generate(random, status);
        int someInt = gen().type(int.class).generate(random, status);

        A a = new A(someString, someInt);

        a.setListOfB(listOfB().generate(random, status));
        return a;
    }
}
```

**Comment by marcoUnited** [comment]
Thank you for the example, this works for me! 
In that case addComponentGenerators() should be protected. Although this would break backwards-compatability (although it really shouldn't as no-one should be using it)

**Comment by pholser** [comment]
`addComponentGenerators()` is `public` because classes from packages "internal" to junit-quickcheck call it (`GeneratorRepository`, in particular). As such, I'm reluctant to rethink the visibility of `addComponentGenerators()`. Perhaps clarifying which methods are for the framework's benefit only will be enough?

**Comment by pholser** [comment]
I'm considering this issue closed with the addition of some Javadoc indicating that some methods on `Generator` are for the framework's use.
