### ISSUE TITLE
Exception with format specifier in failure message

### ISSUE THREAD

**Issue by twistedsquare** [pholser/junit-quickcheck#212]
If a call to fail has part of the message which is an invalid format specifier for String.format, this causes an exception in the shrinker.  To reproduce with 0.8.1:

```
    @Property
    public void prop(int n)
    {
        if (n > 1000000)
            fail("Failure with a %D in the text");
    }
```

Gives:

```
java.lang.AssertionError: java.util.UnknownFormatConversionException: Conversion = 'D'

	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$52(PropertyStatement.java:156)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:88)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:69)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:112)
        ...
Caused by: java.util.UnknownFormatConversionException: Conversion = 'D'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2691)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2720)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.pholser.junit.quickcheck.runner.PropertyFalsified.smallerCounterexampleFound(PropertyFalsified.java:77)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.fail(ShrinkNode.java:120)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:90)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:175)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$52(PropertyStatement.java:152)
```

I think the likely fix is that PropertyFalsified should include the user's message via %s in String.format, rather than concatenating it into the format string.

**Comment by pholser** [comment]
@twistedsquare Thanks for this, and sorry for the trouble. I agree, likely a straightforward correction.

**Comment by pholser** [comment]
@twistedsquare Please have a look at the above PR and let me know what you think.

**Comment by twistedsquare** [comment]
Thanks for the speedy fix -- looks fine to me.  (Love using the library by the way, thanks for making it!)

**Comment by pholser** [comment]
This is in 0.8.2, just released.
