### ISSUE TITLE
Unable to generate random List of integer values

### ISSUE THREAD

**Issue by rubioz** [pholser/junit-quickcheck#52]
Hi, 
first thanks a lot for this awesome project. Unfortunately, I am not able to properly generate list over parametrized types while running 0.5-alpha-1. The signature of my method is:

```java
@Theory public void testWithRandomList(@ForAll List<Integer> digits) 
```

However, digits is filled with ```com.pholser.junit.quickcheck.internal.Zilch``` instead of proper integer values. With arrays it does work. Moreover, this behavior does not appear when running version 0.4.

Thanks a lot!

**Comment by pholser** [comment]
@rubioz Thanks for reporting - I'll try reproducing this and see what's going on.

**Comment by pholser** [comment]
@rubioz With the test class below, and the only project dependencies being junit-quickcheck-core-0.5-alpha-1.jar and junit-quickcheck-generators-0.5-alpha-1.jar (and their transitive dependency closure), this seems to emit integers:

    package com.pholser.scratchpad;

    import com.pholser.junit.quickcheck.ForAll;
    import org.junit.contrib.theories.Theories;
    import org.junit.contrib.theories.Theory;
    import org.junit.runner.RunWith;

    import java.util.List;

    @RunWith(Theories.class)
    public class ListTheories {
        @Theory public void testWithRandomList(@ForAll List<Integer> digits) {
            for (Integer each : digits) {
                System.out.println(each);
            }
        }
    }

Not sure what might be going on. What does your project look like?

**Comment by rubioz** [comment]
I am fulfilling the dependencies from maven, as it  can be seen below:
```
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>com.pholser</groupId>
            <artifactId>junit-quickcheck-core</artifactId>
            <version>0.5-alpha-1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.pholser</groupId>
            <artifactId>junit-quickcheck-generators</artifactId>
            <version>0.5-alpha-1</version>
            <scope>test</scope>
        </dependency>
```

The whole stack trace it shows (with your exact example) is the following:

```java
org.junit.contrib.theories.internal.ParameterizedAssertionError: testWithRandomList("[com.pholser.junit.quickcheck.internal.Zilch@458ad742]" <from [com.pholser.junit.quickcheck.internal.Zilch@458ad742]>)
	at org.junit.contrib.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:215)
	at org.junit.contrib.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:169)
	at org.junit.contrib.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:188)
	at org.junit.contrib.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:142)
	at org.junit.contrib.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:148)
	at org.junit.contrib.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:140)
	at org.junit.contrib.theories.Theories$TheoryAnchor.evaluate(Theories.java:128)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassCastException: com.pholser.junit.quickcheck.internal.Zilch cannot be cast to java.lang.Integer
```

**Comment by pholser** [comment]
Curious. What version of JDK 8 are you using? I have 8u40. I wonder if perhaps there is a problem with prior patch versions?

**Comment by rubioz** [comment]
That was the issue :disappointed_relieved:, I was running 8u05. Updating to yours fixed the issue. 

Thanks!

**Comment by pholser** [comment]
@rubioz No worries. Thanks for your interest! I hope you find the project to be of some value.
