### ISSUE TITLE
IllegalAccessException on $jacocoData when using Fields with Jacoco coverage tool

### ISSUE THREAD

**Issue by richard-melvin** [pholser/junit-quickcheck#55]
Given a test that uses the new Field mechanism:

```java
@Theory
public void originDistance(@ForAll @From(Fields.class) Point p) {
```

then when it is run with coverage turned on, get:

```
com.pholser.junit.quickcheck.internal.ReflectionException: java.lang.IllegalAccessException: Can not set static final [Z field com.github.radm.theories.test.QuickCheckIntegrationTest$Point.$jacocoData to [Z
	at com.pholser.junit.quickcheck.internal.Reflection.reflectionException(Reflection.java:239) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.Reflection.setField(Reflection.java:193) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.generator.Fields.generate(Fields.java:76) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.generator.CompositeGenerator.generate(CompositeGenerator.java:49) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.generator.GenerationContext.generateUsing(GenerationContext.java:55) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.generator.GenerationContext.generate(GenerationContext.java:49) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.generator.RandomTheoryParameterGenerator.generate(RandomTheoryParameterGenerator.java:60) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
	at com.pholser.junit.quickcheck.internal.RandomValueSupplier.getValueSources(RandomValueSupplier.java:57) ~[junit-quickcheck-core-0.5-alpha-3.jar:na]
```

which is presumably due to [this issue](https://github.com/jacoco/jacoco/issues/168). 

Likely other tools would get similar issues. Is it possible to have Fields ignore synthetic members?

**Comment by pholser** [comment]
@richard-melvin I would bet ignoring synthetic members wouldn't be too bad. I'll have a look.

**Comment by pholser** [comment]
@richard-melvin Latest snapshot at oss.sonatype.org has `Fields` generator that should disregard synthetic fields. Let me know how this behaves for you.

**Comment by richard-melvin** [comment]
fast work - I can confirm that resolves the problem, and doesn't seem to cause any other issues.
