### ISSUE TITLE
failed test is not printing out original assertion error

### ISSUE THREAD

**Issue by hmvien** [pholser/junit-quickcheck#99]
I am receiving `java.lang.AssertionError: Property test falsified for args shrunken to []` instead of something like
```
org.junit.ComparisonFailure: 
Expected :name
Actual   :foo
```

**Comment by pholser** [comment]
@hmvien Would you mind to post your test? Thanks!

**Comment by hmvien** [comment]
Certainly!

```
@RunWith(JUnitQuickcheck.class)
public class QuickCheckTest {

    @Property
    public void testOutputDiff(String s) {
        assertEquals(s, "not equal");
    }

}
```

```
java.lang.AssertionError: Property testOutputDiff falsified for args shrunken to []
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.test.QuickCheckTest.testOutputDiff(QuickCheckTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:96)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:73)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:65)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:106)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by hmvien** [comment]
Running junit without quickcheck output the correct results

```
junit.framework.ComparisonFailure: 
Expected :another string
Actual   :not equal
```

**Comment by pholser** [comment]
@hmvien Beginning with 0.6, junit-quickcheck attempts shrinking for failed properties, so that it can find as "small" of a counterexample that makes the property fail. It looks like the shrinker found as "small" a string as it could that caused the property to fail: the zero-length string.

If you want to turn off shrinking for a particular property, set the `shrink` attribute of the `@Property` annotation to `false`.

Would it be helpful to include the message and stack trace from the original failure in addition to the message from the "shrunken" failure?

One risk with shrinking is that it's possible to construct a property that verifies too much, so that a smaller set of values might falsify the property for a reason other than what caused the original failure. I suppose that's a risk I could advertise in the docs.

**Comment by pholser** [comment]
@hmvien However, I think it'd be nice to make the original failure be the "cause" of the assertion error that the shrinking mechanism raises. So, this test:

    @RunWith(JUnitQuickcheck.class)
    public class ShrinkingCompletely {
        @Property(
            maxShrinks = Integer.MAX_VALUE,
            maxShrinkDepth = Integer.MAX_VALUE)
        public void shouldHold(Foo f) {
            assumeThat(f.i(), greaterThan(0));

            assertThat(f.i(), lessThan(1));
        }
    }

would yield something like:

    java.lang.AssertionError: Property shouldHold falsified for args shrunken to [Foo[1]] using initial seeds [-6731889730898940719]
	at com.pholser.junit.quickcheck.runner.ShrinkNode.fail(ShrinkNode.java:103)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:103)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:161)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$25(PropertyStatement.java:135)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:111)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:95)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.AssertionError: 
    Expected: a value less than <1>
         but: <484360715> was greater than <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 22 more

**Comment by hmvien** [comment]
I totally agree! I believe it would be even better if we can move the
original assert message to the top and make it the first class citizen. The
majority of the time that is what is most important. We shouldn't require
developers to scan through the entire stack trace to see the original
error.

**Comment by pholser** [comment]
@hmvien Thanks for your feedback. What do you think of this as a potential revised error message?

    java.lang.AssertionError: Property shouldHold falsified.
    Original failure message: 
    Expected: a value less than <1>
         but: <62877009> was greater than <1>
    Original args: [Foo[62877009]]
    Args shrunken to: [Foo[1]]
    Seeds: [-4327411864500874256]

	at com.pholser.junit.quickcheck.runner.ShrinkNode.fail(ShrinkNode.java:103)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:103)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:161)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$5(PropertyStatement.java:135)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:111)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:95)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.AssertionError: 
    Expected: a value less than <1>
         but: <62877009> was greater than <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.pholser.junit.quickcheck.ShrinkingTest$ShrinkingCompletely.shouldHold(ShrinkingTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 22 more`

**Comment by pholser** [comment]
@hmvien See how the latest 0.7-SNAPSHOT at oss.sonatype.org works for you. Thanks!

**Comment by hmvien** [comment]
Change looks awesome @pholser! Much appreciated!
